fixup! Use importlib.metadata instead of deprecated pkg_resources
```
ERROR: test_load_func (tests.test_session_firefox.TestEntryPoint)
Check whether loaeded function is firefox.load().
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/yanico/yanico/tests/test_session_firefox.py", line 75, in test_load_func
    (entry,) = [e for e in eps["yanico.sessions"] if e.name == "firefox"]
ValueError: too many values to unpack (expected 1)
```